import fs from 'node:fs'

const archivos = ['src/App.jsx', 'server/index.js', 'server/auth.js', 'server/db.js', 'README.md']

const reemplazos = [
  ['apiBase', 'baseApi'],
  ['buildApiUrl', 'construirUrlApi'],
  ['normalizedPath', 'rutaNormalizada'],
  ['initialRegisterForm', 'formularioRegistroInicial'],
  ['initialProfileDraft', 'borradorPerfilInicial'],
  ['initialPropertyDraft', 'borradorPropiedadInicial'],
  ['apiRequest', 'solicitudApi'],
  ['createProfileDraft', 'crearBorradorPerfil'],
  ['createPropertyDraft', 'crearBorradorPropiedad'],
  ['toText', 'aTexto'],
  ['authMode', 'modoAcceso'],
  ['setAuthMode', 'setModoAcceso'],
  ['loginForm', 'formularioInicioSesion'],
  ['setLoginForm', 'setFormularioInicioSesion'],
  ['registerForm', 'formularioRegistro'],
  ['setRegisterForm', 'setFormularioRegistro'],
  ['statusMessage', 'mensajeEstado'],
  ['isSubmitting', 'enviandoFormulario'],
  ['sessionUser', 'usuarioSesion'],
  ['setSessionUser', 'setUsuarioSesion'],
  ['profileDraft', 'borradorPerfil'],
  ['setProfileDraft', 'setBorradorPerfil'],
  ['isSavingProfile', 'guardandoPerfil'],
  ['setIsSavingProfile', 'setGuardandoPerfil'],
  ['propertyDraft', 'borradorPropiedad'],
  ['setPropertyDraft', 'setBorradorPropiedad'],
  ['propertyList', 'listaPropiedades'],
  ['setPropertyList', 'setListaPropiedades'],
  ['isLoadingProperties', 'cargandoPropiedades'],
  ['setIsLoadingProperties', 'setCargandoPropiedades'],
  ['isSavingProperty', 'guardandoPropiedad'],
  ['setIsSavingProperty', 'setGuardandoPropiedad'],
  ['editingPropertyId', 'idPropiedadEditando'],
  ['setEditingPropertyId', 'setIdPropiedadEditando'],
  ['propertyMessage', 'mensajePropiedad'],
  ['setPropertyMessage', 'setMensajePropiedad'],
  ['searchCandidates', 'candidatosBusqueda'],
  ['setSearchCandidates', 'setCandidatosBusqueda'],
  ['searchLoading', 'cargandoBusqueda'],
  ['setSearchLoading', 'setCargandoBusqueda'],
  ['searchMessage', 'mensajeBusqueda'],
  ['setSearchMessage', 'setMensajeBusqueda'],
  ['matchItems', 'coincidencias'],
  ['setMatchItems', 'setCoincidencias'],
  ['matchLoading', 'cargandoCoincidencias'],
  ['setMatchLoading', 'setCargandoCoincidencias'],
  ['matchMessage', 'mensajeCoincidencias'],
  ['setMatchMessage', 'setMensajeCoincidencias'],
  ['roleLabel', 'etiquetaRol'],
  ['handleLoginSubmit', 'manejarEnvioInicioSesion'],
  ['handleRegisterSubmit', 'manejarEnvioRegistro'],
  ['handleLogout', 'manejarCerrarSesion'],
  ['handleProfileSubmit', 'manejarEnvioPerfil'],
  ['handlePropertyEdit', 'manejarEdicionPropiedad'],
  ['handlePropertyReset', 'reiniciarPropiedad'],
  ['handlePropertySubmit', 'manejarEnvioPropiedad'],
  ['handlePropertyDelete', 'manejarEliminarPropiedad'],
  ['refreshSearch', 'refrescarBusqueda'],
  ['handleVote', 'manejarVoto'],
  ['authToken', 'tokenAutenticacion'],
  ['roleData', 'datosRol'],
  ['myVote', 'miVoto'],
  ['theirVote', 'suVoto'],
  ['matchUser', 'usuarioCoincidencia'],
  ['createToken', 'crearToken'],
  ['requireAuth', 'requiereAutenticacion'],
  ['mapProfileRow', 'mapearFilaPerfil'],
  ['loadUserProfile', 'cargarPerfilUsuario'],
  ['loadCurrentProfile', 'cargarPerfilActual'],
  ['buildProfilePreview', 'construirVistaPreviaPerfil'],
  ['buildMatchSummary', 'construirResumenCoincidencia'],
  ['withTransaction', 'conTransaccion'],
  ['Register error:', 'Error en registro:'],
  ['Login error:', 'Error en inicio de sesion:'],
  ['Unhandled Rejection at:', 'Rechazo no controlado en:'],
  ['Uncaught Exception:', 'Excepcion no controlada:'],
  ['API listening on', 'Api escuchando en'],
  ['Initializing database pool with:', 'Inicializando conexion de base de datos con:'],
  ['Unexpected error on idle client', 'Error inesperado en cliente inactivo'],
  ['New client connected to database', 'Nuevo cliente conectado a la base de datos'],
  ['frontend', 'interfaz'],
  ['backend', 'servidor'],
  ['Landing', 'Pagina principal'],
  ['login', 'inicio de sesion'],
]

function escaparRegex(texto) {
  return texto.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

for (const archivo of archivos) {
  let contenido = fs.readFileSync(archivo, 'utf8')
  for (const [origen, destino] of reemplazos) {
    contenido = contenido.replace(new RegExp(`\\b${escaparRegex(origen)}\\b`, 'g'), destino)
  }
  fs.writeFileSync(archivo, contenido)
}
